-- *******
-- Plugins
-- *******

require('lazy').setup {
  spec = {
    require 'plugins.abolish',
    -- require 'plugins.autoclose',
    require 'plugins.blink-cmp',
    require 'plugins.conform',
    -- require 'plugins.copilot',
    require 'plugins.ctrlp',
    require 'plugins.eunuch',
    require 'plugins.ferret',
    require 'plugins.github-preview',
    require 'plugins.gitsigns',
    require 'plugins.indent-blankline',
    require 'plugins.lazydev',
    require 'plugins.lualine',
    -- require 'plugins.mini',
    -- require 'plugins.markdown-preview',
    require 'plugins.mdx',
    require 'plugins.neo-tree',
    -- require 'plugins.noice',
    require 'plugins.nvim-lspconfig',
    -- require 'plugins.nvim-notify',
    require 'plugins.nvim-autopairs',
    require 'plugins.nvim-surround',
    require 'plugins.nvim-treesitter-endwise',
    require 'plugins.nvim-treesitter',
    require 'plugins.splitjoin',
    require 'plugins.tinted',
    require 'plugins.typescript-tools',
    --require 'plugins.todo-comments',
    require 'plugins.which-key',
    require 'plugins.vim-rzip',
  },
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
}
