-- Use [PEP8](http://www.python.org/dev/peps/pep-0008/)
-- XXX: This seems to be getting set in zsh files, plz fix
-- vim.o.softtabstop = 4
-- vim.o.tabstop = 4
-- vim.o.shiftwidth = 4
-- vim.o.textwidth = 79
