#!/bin/sh

set -e

if [[ -f $dir/ctags.pid ]]; then
  exit 1
fi

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
echo $$ > $dir/ctags.pid
git ls-files | ctags --tag-relative -L - -f "$dir/tags" --languages=Ruby,JavaScript
rm $dir/ctags.pid
