
if has("gui_macvim")
  " Unmap Undo/Redo since it messes things up in insert mode
  " This is defined in $VIMRUNTIME/menu.vim
  silent! aunmenu &Edit.&Undo
  silent! aunmenu &Edit.&Redo

  " Get rid of the balloon that usually appears when you hover over a
  " Ruby method, as right now it has an error
  " See: <http://code.google.com/p/macvim/issues/detail?id=342>
  set balloondelay=1000000

  " Interpret the Option as Meta
  set macmeta

  " Size the window so it fills the screen (23" monitor)
  set columns=500
  set lines=100

  " Set font
  set guifont=Droid\ Sans\ Mono\ Slashed\ for\ Powerline:h12
  set linespace=5
  "set guifont=Mensch\ Regular\ for\ Powerline:h12
  "set linespace=5

  set guioptions-=T " disable the toolbars in macvim
  set guioptions-=r " disable right-hand scrollbar
  set guioptions-=L " disable left-hand scrollbar
  set guioptions-=e " disable graphical tabs
  set guioptions+=c " console prompts instead of dialogs

  " unmap macvim menu first
  macmenu Tools.List\ Errors key=<nop>
  nnoremap <D-l> :nohlsearch<CR>
  inoremap <D-l> <C-O>:nohlsearch<CR>
end
