
if has("gui_macvim")
  " Unmap Undo/Redo since it messes things up in insert mode
  " This is defined in $VIMRUNTIME/menu.vim
  silent! aunmenu &Edit.&Undo
  silent! aunmenu &Edit.&Redo

  " Get rid of the balloon that usually appears when you hover over a
  " Ruby method, as right now it has an error
  " See: <http://code.google.com/p/macvim/issues/detail?id=342>
  set balloondelay=1000000

  " Interpret the Option as Meta
  set macmeta

  " Size the window so it fills the screen (23" monitor)
  set columns=500
  set lines=100

  " Set font
  set guifont=Droid\ Sans\ Mono\ Slashed\ for\ Powerline:h12
  set linespace=2
  "set guifont=Mensch\ Regular\ for\ Powerline:h12
  "set linespace=5

  set guioptions-=T " disable the toolbars in macvim
  set guioptions-=r " disable right-hand scrollbar
  set guioptions-=L " disable left-hand scrollbar
  set guioptions-=e " disable graphical tabs
  set guioptions+=c " console prompts instead of dialogs

  " unmap macvim menu first
  macmenu Tools.List\ Errors key=<nop>
  nnoremap <D-l> :nohlsearch<CR>
  inoremap <D-l> <C-O>:nohlsearch<CR>

  " Cmd-based shortcuts for switching tabs
  map <D-j> gT
  map <D-k> gt

  " make it easy to toggle wrapping
  map <M-w> :set invwrap<CR>

  " emulate cmd-return in textmate
  " <http://stackoverflow.com/questions/1526188/how-to-emulate-textmates-command-return-feature-in-vim>
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<nop>
  inoremap <D-CR> <C-O>o

  " Map Command-# to switch tabs
  map  <D-0> 0gt
  imap <D-0> <Esc>0gt
  map  <D-1> 1gt
  imap <D-1> <Esc>1gt
  map  <D-2> 2gt
  imap <D-2> <Esc>2gt
  map  <D-3> 3gt
  imap <D-3> <Esc>3gt
  map  <D-4> 4gt
  imap <D-4> <Esc>4gt
  map  <D-5> 5gt
  imap <D-5> <Esc>5gt
  map  <D-6> 6gt
  imap <D-6> <Esc>6gt
  map  <D-7> 7gt
  imap <D-7> <Esc>7gt
  map  <D-8> 8gt
  imap <D-8> <Esc>8gt
  map  <D-9> 9gt
  imap <D-9> <Esc>9gt

  " Command-][ to increase/decrease indentation
  vmap <D-]> >gv
  vmap <D-[> <gv

  " command-T
  macmenu &File.New\ Tab key=<nop>
  map <D-t> :CommandT<CR>

  nnoremap <D-r> :NERDTreeToggle<CR>   " from atmos
  " open the nerd tree window first, in CWD, so the find doesn't change
  " the tree root.
  nnoremap <D-R> :NERDTree<CR><C-w>p:NERDTreeFind<CR>

  " Command-/ to toggle comments
  map <D-/> <plug>NERDCommenterToggle<CR>
  imap <D-/> <Esc><plug>NERDCommenterToggle<CR>i
end
