#!/bin/bash

for file in base history fancy_prompt handy_shortcuts autojump; do
  source ~/.profile.d/$file
done

for file in dev etc osx mysql java echonest perl6 git ruby rvm node vim clojure; do
  source ~/.profile.d/$file
done
