source ~/.zsh/asdf
source ~/.zsh/autojump
source ~/.zsh/bindings
source ~/.zsh/clojure
source ~/.zsh/colors
source ~/.zsh/cucumber
source ~/.zsh/direnv
source ~/.zsh/fzf
source ~/.zsh/git
source ~/.zsh/google-cloud-sdk
source ~/.zsh/haskell
source ~/.zsh/history
source ~/.zsh/java
source ~/.zsh/perl6
source ~/.zsh/rust
source ~/.zsh/tmux
source ~/.zsh/travis
source ~/.zsh/unicode
source ~/.zsh/vim
source ~/.zsh/zmv
source ~/.zsh/zzz_aliases
source ~/.zsh/zzz_functions

source ~/.zsh/prompt

if [[ -f ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi
