# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Never EVER ask me to update, this is just effing annoying
DISABLE_AUTO_UPDATE=true

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow hub)

# Set sensible starting path
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Load this first because the suvash theme depends on having rbenv available
source ~/.zsh/rbenv

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Provide our own theme
source ~/.zsh/mcmire.zsh-theme

# Disable autocorrection, it's SUPER annoying
unsetopt correct_all
# Disable oh-my-zsh's default, global history settings
unsetopt share_history
unsetopt append_history
unsetopt inc_append_history

for file in ~/.zsh/*; do
  source $file
done
