#!/bin/bash

set -eo pipefail

python36_dir="$(pyenv prefix)/lib/python3.6"
python37_dir="$(pyenv prefix)/lib/python3.7"

python-dir() {
  if [[ -d $python37_dir ]]; then
    echo $python37_dir
  else
    echo $python36_dir
  fi
}

powerline-daemon -q
tmux source-file "$(python-dir)/site-packages/powerline/bindings/tmux/powerline.conf"
